import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js';
import {getFirestore,collection,doc,setDoc,updateDoc,deleteDoc,onSnapshot,writeBatch,serverTimestamp} from 'https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js';

const config={apiKey:'AIzaSyBbvUJsT1AEtLK7zKYQ8GZSXgw4srW61iU',authDomain:'lista-de-compras-6b8c6.firebaseapp.com',projectId:'lista-de-compras-6b8c6',storageBucket:'lista-de-compras-6b8c6.firebasestorage.app',messagingSenderId:'923961365656',appId:'1:923961365656:web:f0dad41f0ed53ed5b32ced'};
const app=initializeApp(config),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
provider.setCustomParameters({prompt:'select_account'});
const itemsRef=collection(db,'lists','main','items');
const CATS=['Carnicería','Verdulería','Supermercado','Dietética','Ferretería','Mercería','Librería','Farmacia','Otros'];
const META={Carnicería:['🥩','#9f4f46'],Verdulería:['🥬','#4f7a5b'],Supermercado:['🛒','#8a6a3e'],Dietética:['🌾','#7b6b45'],Ferretería:['🔧','#596675'],Mercería:['🧵','#7d5f76'],Librería:['✏️','#4f6980'],Farmacia:['💊','#4f7b77'],Otros:['📦','#6d6964']};
let user=null,items=[],editingId=null,activeCategory='',unsubscribe=null;
const $=id=>document.getElementById(id);
const el={authGate:$('authGate'),app:$('appContent'),login:$('loginBtn'),authMessage:$('authMessage'),account:$('accountBtn'),initial:$('accountInitial'),sync:$('syncStatus'),name:$('itemName'),qty:$('itemQty'),cat:$('itemCat'),note:$('itemNote'),add:$('addBtn'),cancel:$('cancelEditBtn'),filter:$('filter'),filterClear:$('filterClear'),clearDone:$('clearDone'),list:$('listContainer'),stats:$('stats'),export:$('exportBtn'),import:$('importBtn'),importFile:$('importFile'),quick:$('quickCats'),share:$('shareBtn'),formTitle:$('formTitle')};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function sync(text,state='online'){el.sync.innerHTML=`<span class="status-dot ${state}"></span>${text}`;}
function styleCat(node,cat){node.style.setProperty('--cat-accent',(META[cat]||META.Otros)[1]);}
function refreshChips(){el.quick.querySelectorAll('.chip').forEach(b=>b.classList.toggle('active',b.dataset.category===activeCategory));}
function initCats(){const all=document.createElement('button');all.className='chip all-chip active';all.dataset.category='';all.innerHTML='<span>☰</span><span>Todos</span>';all.onclick=()=>{activeCategory='';el.filter.value='';refreshChips();render();};el.quick.appendChild(all);for(const cat of CATS){el.cat.add(new Option(cat,cat));const b=document.createElement('button');b.className='chip';b.dataset.category=cat;b.innerHTML=`<span class="chip-icon">${META[cat][0]}</span><span>${cat}</span>`;b.onclick=()=>{activeCategory=activeCategory===cat?'':cat;el.filter.value=activeCategory;refreshChips();render();};el.quick.appendChild(b);}el.cat.value=localStorage.getItem('shopping_last_category')||CATS[0];}
function resetForm(){editingId=null;el.name.value='';el.qty.value='';el.note.value='';el.formTitle.textContent='Agregar producto';el.add.innerHTML='<span>＋</span> Agregar';el.cancel.classList.add('hidden');}
async function save(){const name=el.name.value.trim();if(!name||!user)return;localStorage.setItem('shopping_last_category',el.cat.value);sync('Guardando…','pending');const old=items.find(i=>i.id===editingId);const id=editingId||uuid();await setDoc(doc(itemsRef,id),{name,qty:el.qty.value.trim(),category:el.cat.value,note:el.note.value.trim(),done:old?.done||false,created:old?.created||Date.now(),updated:Date.now(),updatedBy:user.email,serverUpdatedAt:serverTimestamp()},{merge:true});resetForm();}
function edit(id){const i=items.find(x=>x.id===id);if(!i)return;editingId=id;el.name.value=i.name;el.qty.value=i.qty||'';el.cat.value=i.category||CATS[0];el.note.value=i.note||'';el.formTitle.textContent='Editar producto';el.add.textContent='Guardar cambios';el.cancel.classList.remove('hidden');scrollTo({top:0,behavior:'smooth'});}
async function toggle(id){const i=items.find(x=>x.id===id);if(i)await updateDoc(doc(itemsRef,id),{done:!i.done,updated:Date.now(),updatedBy:user.email,serverUpdatedAt:serverTimestamp()});}
async function remove(id){const i=items.find(x=>x.id===id);if(i&&confirm(`¿Eliminar “${i.name}”?`))await deleteDoc(doc(itemsRef,id));}
function row(i){const li=document.createElement('li');li.className=`item${i.done?' done':''}`;const cb=document.createElement('input');cb.type='checkbox';cb.checked=i.done;cb.onchange=()=>toggle(i.id).catch(error);const text=document.createElement('div');text.innerHTML=`<div class="item-name">${esc(i.name)}</div>${i.note?`<div class="item-note">${esc(i.note)}</div>`:''}`;const qty=document.createElement('span');qty.className='item-qty';qty.textContent=i.qty||'';const acts=document.createElement('div');acts.className='item-actions';const ed=document.createElement('button');ed.className='action-icon edit-icon';ed.textContent='✏️';ed.onclick=()=>edit(i.id);const del=document.createElement('button');del.className='action-icon delete-icon';del.textContent='🗑️';del.onclick=()=>remove(i.id).catch(error);acts.append(ed,del);li.append(cb,text,qty,acts);return li;}
function render(){const q=el.filter.value.toLowerCase().trim();const visible=items.filter(i=>!q||[i.name,i.category,i.note].some(v=>(v||'').toLowerCase().includes(q))).sort((a,b)=>Number(a.done)-Number(b.done)||(a.category||'').localeCompare(b.category||'')||(b.created||0)-(a.created||0));el.list.innerHTML='';if(!visible.length)el.list.innerHTML='<div class="card empty">No hay productos para mostrar.</div>';else{const groups=visible.reduce((a,i)=>((a[i.category||'Otros']??=[]).push(i),a),{});for(const cat of Object.keys(groups).sort()){const s=document.createElement('section');s.className='group';const h=document.createElement('h2');h.className='group-title';h.innerHTML=`<span class="category-icon">${(META[cat]||META.Otros)[0]}</span><span>${esc(cat)}</span><span class="category-count">${groups[cat].length}</span>`;styleCat(h,cat);const ul=document.createElement('ul');ul.className='item-list';groups[cat].forEach(i=>ul.appendChild(row(i)));s.append(h,ul);el.list.appendChild(s);}}el.stats.textContent=`${items.length} ítems · ${items.filter(i=>!i.done).length} pendientes`;}
function error(e){console.error(e);sync('Error','error');alert(e?.message||'No se pudo completar la operación.');}
async function login(){el.authMessage.textContent='Abriendo Google…';try{await signInWithPopup(auth,provider);}catch(e){if(['auth/popup-blocked','auth/operation-not-supported-in-this-environment'].includes(e.code))await signInWithRedirect(auth,provider);else{el.authMessage.textContent=`${e.code||''} ${e.message||''}`;}}}
function subscribe(){if(unsubscribe)unsubscribe();sync('Sincronizando…','pending');unsubscribe=onSnapshot(itemsRef,{includeMetadataChanges:true},snap=>{items=snap.docs.map(d=>({id:d.id,...d.data()}));render();sync(snap.metadata.fromCache?'Sin conexión':'Sincronizado',snap.metadata.fromCache?'offline':'online');},error);}
function shareText(){const pending=items.filter(i=>!i.done),lines=['🛒 Lista de compras'];const groups=pending.reduce((a,i)=>((a[i.category||'Otros']??=[]).push(i),a),{});for(const cat of Object.keys(groups).sort()){lines.push(`\n${cat}:`);groups[cat].forEach(i=>lines.push(` • ${i.name}${i.qty?` x ${i.qty}`:''}${i.note?` (${i.note})`:''}`));}return lines.join('\n');}
el.login.onclick=login;el.account.onclick=()=>confirm('¿Cerrar sesión?')&&signOut(auth);el.add.onclick=()=>save().catch(error);el.cancel.onclick=resetForm;el.cat.onchange=()=>localStorage.setItem('shopping_last_category',el.cat.value);el.filter.oninput=()=>{activeCategory='';el.filterClear.classList.toggle('hidden',!el.filter.value);refreshChips();render();};el.filterClear.onclick=()=>{el.filter.value='';activeCategory='';refreshChips();render();};el.clearDone.onclick=async()=>{const done=items.filter(i=>i.done);if(done.length&&confirm(`¿Eliminar ${done.length} productos comprados?`)){const batch=writeBatch(db);done.forEach(i=>batch.delete(doc(itemsRef,i.id)));await batch.commit();}};el.share.onclick=async()=>{const text=shareText();if(navigator.share)await navigator.share({text});else window.open(`https://wa.me/?text=${encodeURIComponent(text)}`);};el.export.onclick=()=>{const blob=new Blob([JSON.stringify(items,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='lista_compras.json';a.click();URL.revokeObjectURL(url);};el.import.onclick=()=>el.importFile.click();el.importFile.onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const arr=JSON.parse(await file.text());const batch=writeBatch(db);arr.forEach(i=>batch.set(doc(itemsRef,i.id||uuid()),{...i,updated:Date.now(),updatedBy:user.email,serverUpdatedAt:serverTimestamp()},{merge:true}));await batch.commit();e.target.value='';};
initCats();getRedirectResult(auth).catch(e=>el.authMessage.textContent=e.message);onAuthStateChanged(auth,u=>{user=u;if(u){el.authGate.classList.add('hidden');el.app.classList.remove('hidden');el.initial.textContent=(u.displayName||u.email||'U')[0].toUpperCase();subscribe();}else{unsubscribe?.();items=[];el.app.classList.add('hidden');el.authGate.classList.remove('hidden');}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=12',{updateViaCache:'none'}).then(r=>r.update()));
